---
name: Lizard Runner
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lizard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lizard Runner
        uses: Uno-Takashi/Lizard-Runner@v3
