---
name: Release Please

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      #- name: Generate a token
      #  id: generate_token
      #  uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1.10.3
      #  with:
      #    app-id: ${{secrets.APP_ID}}
      #    private-key: ${{secrets.APP_PRIVATE_KEY}}
      - uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4.1.3
        id: release
        with:
          #token: ${{ steps.generate_token.outputs.token }}
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
#  deploy:
#    needs: release-please
#    if: ${{ needs.release-please.outputs.release_created == 'true' }}
#    runs-on: ubuntu-latest
#    permissions:
#      id-token: write
#      contents: read
#      pull-requests: write
#    steps:
#      - name: Check out repository code
#        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
